#检查更新 true为启用 false为禁用
checkUpdate: true

message:
  enable: '§b已启用.'
  disable: '§7已卸载.'
  prefix: '§8[§3ILoreEdit§8] §c-> '
  helpMsg:
    - '§e===========§bILoreEdit§e==========='
    - '§a/lore name <名字> §7---- §b设置物品名字'
    - '§a/lore add <内容> §7---- §b添加一行Lore'
    - '§a/lore set <行号> <内容> §7---- §b修改指定行的Lore'
    - '§a/lore ins <行号> <内容> §7---- §b在指定行插入Lore'
    - '§a/lore del [行号] §7---- §b删除指定行的Lore,不指定行号则删除末行'
    - '§a/lore clear name §7---- §b清除物品名字'
    - '§a/lore clear lore §7---- §b清除所有Lore'
    - '§a/lore clear model §7---- §b清除自定义模型数据'
    - '§a/lore import <模板名> §7---- §b导入指定的模板'
    - '§a/lore export <模板名> §7---- §b导出到指定的模板'
    - '§a/lore owner <玩家名> §7---- §b修改头颅主人'
    - '§a/lore model <模型数据> §7---- §b设置自定义模型数据'
    - '§e/ILoreEdit help §7---- §a查看指令帮助'
    - '§e/ILoreEdit reload §7---- §a重载插件配置'
    - '§e/ILoreEdit version §7---- §a查看插件版本'
  canOnlyPlayer: '§b本命令只能玩家使用!'
  argsError: '§c错误的命令参数!'
  reloaded: '§a配置文件重载完成.'
  noItem: '§d你确定你手里有物品???'
  editDisplayName: '§a已修改物品显示名.'
  addLore: '§a已添加Lore.'
  noLore: '§b该物品没有Lore,你要修改什么?'
  invalidLine: '§4你输入的行号不是一个有效的数字.'
  errorLine: '§b你数数一共有几行···'
  zeroLine: '§b行数从1开始.'
  setLore: '§a已修改Lore.'
  noLore-ins: '§b该物品没有Lore,你想怎么插入?'
  insLore: '§a已插入Lore.'
  noLore-del: '§b该物品没有Lore,你要删除啥?'
  delLore: '§a已删除Lore.'
  clearDisplayName: '§a已清除物品显示名.'
  clearLore: '§a已清除Lore.'
  saveError: '§c保存修改失败,请重试.'
  usage: '§6用法:'
  usageEditLore: '§e/lore §3<§aname§7|§aadd§7|§aset§7|§ains§7|§adel§7|§aclear§7|§aimport§7|§aexport§7|§aowner§7|§amodel§3> §7- 使用/ile help查看详细帮助'
  usageILoreEdit: '§e/ILoreEdit §3<§ahelp§c|§aversion§c|§areload§3>'
  templateNotExist: '§c此模板不存在!'
  templateImported: '§a已导入模板.'
  noExport: '§e你手中的物品没什么可导出的.'
  templateExported: '§a已导出至模板.'
  noSkull: '§d你确定你手里拿的是头颅???'
  changedOwner: '§a已修改头颅主人.'
  invalidTemplateName: '§c无效的模板名称!'
  notSupport: '§c服务器版本过低,不支持设置自定义模型数据'
  invalidData: '§4你输入的模型数据不是一个有效的数字.'
  setModelData: '§a已设置自定义模型数据.'
  clearModelData: '§a已清除自定义模型数据.'
  foundNewVersion: '§c发现新版本可用! §b当前版本: {current} §d最新版本: {latest}'
  downloadLink: '§a下载地址: '
  majorUpdate: '§e(有大更新)'
  checkUpdateFailed: '§e检查更新失败, 状态码: '
  checkUpdateException: '§4检查更新时发生IO异常.'